BoletoNet/boletonet

- src/Boleto.Net/BoletoImpressao/BoletoBancario.cs
Baixei o projeto para minha máquina e ao tentar rodar o site MVC de exemplo, acontecia um erro ao selecionar  qualquer banco no dropdown. As imagens dos bancos são carregadas usando reflection e não poderão ser salvas da forma como está hoje, pois quando são retornadas são um UnmanagedMemoryStream. Adicionei um método para copiar o stream do projeto Boleto.Net e escreve-lo em disco conforme idéia inicial do código.
> Fix: Erro ao tentar salvar imagens localizadas no assembly Boleto.Net

- src/Boleto.Net/Arquivo/Reader/TextPosReader.cs
Para evitar que a build no AppVeyor quebre, forcei a cultura que deve ser utilizada para conversão de números.
> Indicando cultura no TextPosReader na conversão números

- src/Boleto.Net.Testes/BancoBrasil/BancoBrasil17027Teste.cs
- src/Boleto.Net.Testes/Boleto.Net.Testes.csproj
- src/Boleto.Net/Banco/Banco_Brasil.cs
- src/Boleto.Net/BoletoImpressao/BoletoBancario.cs
O Banco do Brasil liberou o uso da carteira 17 com vairação 027 mas não está disponível na validação do Boleto.Net.
> Adicionando a carteira 17-027 para Banco do Brasil

- src/Boleto.Net/Banco/Banco_Caixa.cs
Registro trailer do arquivo remessa do banco Caixa (CNAB 240 - SIGCB)
estava sendo gerado com 246 posições.
> Alteração registro trailer - banco Caixa

- src/Boleto.Net/Banco/Banco_Santander.cs
Ao validar as instruções na geração do arquivo de remessa (CNAB 400 -
Santander) está sendo acessado o index 1 de um array que pode ter só UMA
posição.
> Remessa Santander - validar se tem duas instruções

- src/Boleto.Net/Util/Utils.cs
Forçar o Utils.ToDateTime utilizar a cultura brasileira para evitar problemas de conversão de datas em servidores que fiquem com outras regiões configuradas por padrão. Como o arquivo CNAB segue sempre o padrão DD-MM-YYYY esse ajuste não apresenta mudança significativa para os demais usuários e funcionalidades do sistema.
> Forçar o Utils.ToDateTime utilizar a cultura brasileira

- src/Boleto.Net.MVC/Models/Exemplos.cs
- src/Boleto.Net/Banco/Banco_HSBC.cs
Erro na validação do boleto quando o Nosso Número é maior que 2147483647
(Int32.MaxValue)
> Correção overflow conversão nosso número para int32

- src/Boleto.Net/Banco/Banco_Itau.cs
Em um dos cenários de teste, quando passou o valor do Nosso Número como uma string vazia, quando a execução chega nesse ponto do código, no formato anterior o 'Convert.ToInt32' cai na exceção de todo esse bloco de código que retorna a mensagem padrão 'Erro ao validar boletos'.
Porém, no meu cenário é interessante tratar esse situação especificamente, verificando se o Nosso Número é um inteiro válido antes de prosseguir, e caso não seja, retornar uma exceção com uma mensagem mais clara de onde está o erro (no caso, no Nosso Número).
> Adicionada verificação no Nosso Número do Banco Itaú

- src/Boleto.Net/Banco/Banco_Brasil.cs
- src/Boleto.Net/Util/Extensions.cs
Tratamento de exceção para convênios do BB.
Quando o código do convênio é informado incorretamente, não existe um tratamento específicio, sendo necessária realizar depuração para encontrar o erro. Foi feito um tratamento para alertar o usuário quanto a este erro.
> Tratamento de exceção para convênios do BB

- src/Boleto.Net/Banco/Banco_HSBC.cs
Corrigido número de caracteres do campo "Nosso Número" para carteira CSB (10). Havia sido alterado indevidamente para 13 caracteres, sendo que esta alteração tem validade apenas para carteira CNR (ver documentação abaixo).
Alterada a criação do código de barras para incluir o dígito verificador da conta. Anteriormente estava considerando apenas o número da conta.
Alterada a formatação da linha digitável para considerar 10 caracteres no campo "Nosso Número" para carteira CSB. Além disso, foi alterada a seção FFFFFFF da linha digitável para considerar também o dígito verificador da conta. Anteriormente estava considerando apenas o número da conta.
Ver documentação da carteira CSB em <https://www.hsbc.com.br/1/PA_esf-ca-app-content/content/hbbr_pws/pt/para-sua-empresa/pagamentos-e-recebimento …
> HSBC: adequações carteira CSB

- src/Boleto.Net/BoletoImpressao/BoletoBancario.cs
Use o método :
`MontaBytesListaBoletosPDF()    ` 
Passando uma lista de objetos do tipo `BoletoBancario` receba devolta um `byte[]` com `PDF` já pronto para download ou salvamento do arquivo, observe que o método é bem simples, e tem umas opções
a mais:  `CustomSwitches` pode ser visto em [wkhtmltopdf Manual](http://wkhtmltopdf.org/usage/wkhtmltopdf.txt)
`tituloPDF` insere um título na primeira página dos boletos,
`PretoBranco` tipo de impressão, preto e branco ou colorido.
```
byte[] PdfBytes = new BoletoBancario().MontaBytesListaBoletosPDF(Boletos, "Boletos Bancários", CustomSwitches, "Boletos Bancários");
```
**## Mais instruções  de uso no final do Issue:**  #165
> Adicionado Geração do PDF de vários Boletos

- src/Boleto.Net/Util/Utils.cs
**new Cedente(cedenteCNPJ, cedenteNome, cedenteAgencia, cedenteConta)**
esse construtor faz com que os digitos sejam nulos e falhem naquelas verificações da classe Utils. Então no boleto vai sair algo parecido com: 0123-/...
> Melhoria: Permitir utilizar construtor sem ter que atribuir digito = ""

- src/Boleto.Net/Banco/Banco_Nordeste.cs
A equipe de homologação do BNB solicitou a alteração do número da carteira para código da operação na exibição da carteira no boleto. Onde a carteira 4 passará a ser exibida o código de operação equivalente que é 21.
> Boleto BNB nº da carteira para cod da operação

- src/Boleto.Net/Banco/Banco_Brasil.cs
- src/Boleto.Net/Boleto/Boleto.cs
Implementado seguindo a ideia proposta https://github.com/BoletoNet/boletonet/issues/253 para abrir a possibilidade de definir por boleto a Modalidade de Cobrança que pode variar na mesma carteira por exemplo a 17
1 – para carteira 11/12 na modalidade Simples;
2 ou 3 – para carteira 11/17 modalidade Vinculada/Caucionada e carteira 31;
4 – para carteira 11/17 modalidade Descontada e carteira 51; 
7 – para carteira 17 modalidade Simples.
> Banco do Brasil - Modalidade de Cobrança por boleto

- src/Boleto.Net/Banco/Banco_Cecred.cs
- src/Boleto.Net/Util/Utils.cs
- Ajustado retorno que não estava convertendo valores em decimal removendo as casas decimais ex:
> `Convert.ToInt64("000012079") / 100 = 120
Convert.ToDecimal("000012079")/100 = 120.79`
> BANCO CECRED - Conversão de valores decimais

- src/Boleto.Net/Banco/Banco_Santander.cs
Alterado para 8 o limite de dígitos máximo da conta do cedente do banco SANTANDER. Visto que segundo manual, o limite de dígitos da conta é 8.
> Alterado limite de digitos cedente banco SANTANDER

- src/Boleto.Net/Banco/Banco_Itau.cs
- src/Boleto.Net/BoletoImpressao/BoletoBancario.cs
Possibilitar ao boleto.net a criação e configuração do pedido de baixa do Banco Itaú
Revisions 12825, 12826 e 12829.
Correção da geração da remessa do CNAB 109 do Itaú, para gerar o codigo identificador na empresa.
> Possibilitar ao boleto.net a criação e configuração do pedido de baixa do Banco Itaú

- README.md
- Removendo icone de contagem de download do nuget pois isso não está funcionando mais. Referência: NuGet/Home#2596
> Removendo ícone

- src/Boleto.Net/Banco/Banco_BankBoston.cs
- src/Boleto.Net/Banco/Banco_Bradesco.cs
- src/Boleto.Net/Banco/Banco_Brasil.cs
- src/Boleto.Net/Banco/Banco_HSBC.cs
- src/Boleto.Net/Banco/Banco_Itau.cs
- src/Boleto.Net/Banco/Banco_Santander.cs
- src/Boleto.Net/Banco/Banco_Sicoob.cs
- src/Boleto.Net/Util/Extensions.cs
Em sistemas operacionais em inglês (como está o meu), isso pode falhar tentar remover a virgula da forma como estava antes e imprimir um ponto ao invés disso.
Como em alguns servidores não há permissão para se alterar a cultura da _thread_, achei melhor criar um método de extensão para fazer o tratamento.
Aqui está um exemplo para efeitos de comparação:
https://dotnetfiddle.net/RroVux
> Refatoração: Removendo virgula dos decimais

- src/Boleto.Net/Banco/Banco_Sicredi.cs
- src/Boleto.Net/Boleto/EspecieDocumento/EspecieDocumento_Sicredi.cs
Atualizações do banco do Sicred para homologação da remessa e retorno
com o banco
Padronizando código do banco Sicred para ficar conforme o padrão dos
outros bancos. Revision 17506.
Formatação do dígito do nosso número para gerar detalhe da remessa
CNAB400. Revision 17512, 17513 e 17514.
Configuração do código da ocorrência para gerar detalhe da remessa
CNAB400. Revision 17517.
> Atualizações do banco do Sicred para homologação da remessa e retorno com o banco

- src/Boleto.Net/Arquivo/ArquivoRemessaCNAB400.cs
- src/Boleto.Net/Banco/Banco_Itau.cs
4790 - Gerar o seguimento de detalhe opcional de multa do banco Ítau,
400 posições, quando for informado o percentual de multa do título.
Revision 18309.
> Multa opcional no banco Itau

- src/Boleto.Net/Banco/Banco_Caixa.cs
Issue que explica a alteração do commit referente à quantidade de registros no lote e no arquivo https://github.com/BoletoNet/boletonet/issues/286
Mensagem da empresa de homologação
_2 - Na primeira linha posição 192 a 211 contém REMESSAPROCUCAO e o correto é ter REMESSA-PRODUCAO._ 
Alterações efetuadas devido à homologação do mês de **novembro de 2016**
> Fix bug Caixa RemessaCNAB240SIGCB(nº de registros no lote e hifen da 'REMESSA-PRODUCAO')

- src/Boleto.Net/Banco/Banco_Caixa.cs
**Data do crédito deverá ser preenchido com zeros**
LEIAUTE DE ARQUIVOS – CNAB240 14/10/2015
http://www.caixa.gov.br/Downloads/cobranca-caixa/Manual_Leiaute_CNAB240_SIGCB.pdf
Issue relatando bug do _valor total dos títulos em carteira_ https://github.com/BoletoNet/boletonet/issues/239
> Remessa CEF CNAC240SIGCB - Data de crédito e valor total dos títulos em carteira

- src/Boleto.Net/Arquivo/ArquivoRemessaCNAB240.cs
- src/Boleto.Net/Banco/Banco_Caixa.cs
- src/Boleto.Net/Util/Utils.cs
Adicionado Segmento R do CNAB240 SIGCB da CAIXA com o valor da multa por valor fixo ou porcentagem.
Adicionado a troca de caracter especial para espaço e não somente remover o caracter, o que causava diminuição da linha das remessas e troca de posição de campos. Adicionado os caracteres válidos nos arquivos . , \ @ -
> Multa para CNAB240 CAIXA SIGCB e correção da substituição de Caracteres Especiais

- src/Boleto.Net/Banco/Banco_Sicredi.cs
Código estava pela metade e foi feita correção para juntar os valores e enviar juntamente com o DV do Nosso Número como pede o Manual do CNAB400 pela SICREDI.
> CNAB400 SICREDI - Correção na geração do Dígito Verificador do Nosso Número na Remessa

- src/Boleto.Net/Banco/Banco_Nordeste.cs
Estava convertendo valores decimais usando ```Convert.ToInt64```, foi alterado para ```Convert.ToDecimal```
> Fix bug - Retorno cnab400 Banco do Nordeste - Valores sem casa decimais

- src/Boleto.Net/Banco/Banco_Itau.cs
Deixar o nome do sacador avalista em branco na geração do arquivo de remessa CNAB400 do banco Itaú conforme. Vide #290.
> CNAB400 Itaú deixar nome do sacador avalista em branco

- src/Boleto.Net/Boleto/EspecieDocumento/EspecieDocumento.cs
Ajuste realizado para não ocorrer NullReferenceException nas chamadas realizadas no método ValidaSigla().
Embora haja o tratamento da exceção no método, é uma boa prática evitar a ocorrência de Exceptions sempre que possível.
> Ajuste para evitar NullReferenceException em objeto Sigla

- src/Boleto.Net/Banco/AbstractBanco.cs
- src/Boleto.Net/Banco/Banco_Caixa.cs
- src/Boleto.Net/Banco/Banco_Sicredi.cs
- src/Boleto.Net/Enums/TipoOcorrenciaRemessa.cs
Adição do tipo de ocorrência de Remessa 47 - Alteração do Valor Nominal do Título utilizado no manual da FEBRABAN v.10.2.
Alteração banco Sicredi no CNAB400 para utilizar no novo método de obtenção do código do tipo movimentação, bem como o da Caixa no CNAB240.
Alteração do Método ObterCodigoDaOcorrencia para verificar também se o Código da Ocorrência não está vazio.
> Novo Código Movimentação Remessa (47 da FEBRABAN) e Alteração Sicredi e Caixa

- src/Boleto.Net/Html.Designer.cs
- src/Boleto.Net/Html.resx
Ao imprimir os boletos, o campo Boleto.UsoBanco não estava sendo exibido, pois no HTML estava faltando a utilização da variável @USODOBANCO. Corrigi o Html.resx para que tal variável seja exibida adequadamente na impressão do HTML ou PDF.
> Correção do HTML que estava sem o campo @USODOBANCO

- src/Boleto.Net/Banco/Banco_Caixa.cs
Correção Remessa CAIXA CNAB240 para pegar Código do Movimento em todos os segmentos programados.
Além do P que já estava correto.
> Correção Remessa CAIXA CNAB240 - Código do Movimento

- src/Boleto.Net/Banco/Banco_Itau.cs
Alteração no método GerarDetalheRemessaCNAB400 da classe Banco_Itau, pois o valor da identificação do título aceito ou não aceito está com o valor fixo "A".
> Alteração de valor fixo do identificador de título aceito no arquivo de remessa Cnab400 Itaú

- src/Boleto.Net/Banco/Banco_Sicoob.cs
Função NossoNumeroFormatado criada para uso em geração do seguimento detalhe P CNAB240.
Alteração na função GerarDetalheSegmentoPRemessa , linha onde o nosso numero é informado, alterada com o uso da nova função criada.
O problema foi encontrado pois após homologação do arquivo juntamente com o sistema do banco o arquivo foi processado com sucesso, mas os boletos não estavam sendo registrados devido a geração errada da posição 38 a 57(nosso numero) , que deve seguir as regras 
pos 38 a 47(10)  - nosso numero com digito verificador 
pos 48 a 49(2) - numero parcela
pos 50 a 51(2) - modalidade
pos 52 a 52(1) - tipo formulário 
pos 53 a 57(5) - brancos 
No modelo antigo estava sendo informado apenas o nosso numero sem o digito verificador com zeros a esquerda.
> Correção da geração no campo nosso numero pos 38 a 57

- src/Boleto.Net/Banco/Banco_Brasil.cs
Arquivo de remessa CNAB 400 - Banco do Brasil.
Quando os dias de protesto forem mais do que 5, deve ser informado o número de dias nas posições 392 a 393.
> Adicionado dias de protesto no arquivo de remessa BB 400

- src/Boleto.Net/Banco/Banco_Brasil.cs
Alteração para arquivo remessa do Banco do Brasil, no header onde estava fixo na variação 019 e no trailer que faltou adicionar 1.
> Atualização remessa Brasil 17-027

- src/Boleto.Net/Arquivo/ArquivoRemessaCNAB240.cs
- src/Boleto.Net/Banco/Banco_Brasil.cs
- src/Boleto.Net/Banco/Banco_Cecred.cs
Conforme outros bancos e histórico de alterações
1- Aqui mudou para somar +1 @LeandroCDS  https://github.com/BoletoNet/boletonet/commit/47d0e5fe10e36b65e0340d6b3c3880032d8c6ad3
2- Aqui remover a soma +1 e deixou comentado uma region com informações de somas @ecfenix1  https://github.com/BoletoNet/boletonet/commit/6acb02ccc921a7490be87af200ec5b0392b7d712
3- Aqui voltamos a somar +1 @hericss https://github.com/BoletoNet/boletonet/commit/7ce9d3f38a3e73d088b89e3c2ee4437a4288f74d
Obs: outros bancos não existe essa soma +1 no método GerarTrailerLoteRemessa, quem controla essa soma é o ArquivoRemessaCNAB240.cs linha 290
> BB Remessa 240 - Padronizado contagem de registro 240

- src/Boleto.Net/Banco/Banco_Bradesco.cs
- src/Boleto.Net/Banco/Banco_Brasil.cs
- src/Boleto.Net/Banco/Banco_Itau.cs
Como o campo NumeroControle é novo (foi adicionado faz menos de um ano) e talvez não é tão conhecido, melhor que seja opcional. Se o valor for setado, será usado. Se não, permanece o comportamento anterior, de usar o NumeroDocumento.
> Remessa CNAB400: Tenta usar NumeroControle. Se não houver, usa valor anterior

- src/Boleto.Net/Boleto/EspecieDocumento/EspecieDocumento_BancoBrasil.cs
Nos boletos emitidos para o Banco do Brasil
Preciso informar uma especie de documento de divida ativa do estado [DAE]
Para atender uma necessidade existente no órgão do estado em que eu trabalho
O problema existia porque na lista de enumeradores não havia os de Divida Ativa do Estado, Município e União.
> Adicionar na lista de enum do BB, [DAE, DAM, DAU]

- src/.vs/config/applicationhost.config
- src/Boleto.Net.Arquivo/Main.Designer.cs
- src/Boleto.Net.Arquivo/Main.cs
- src/Boleto.Net.Arquivo/NBoleto.cs
- src/Boleto.Net/Banco/Banco_Sicredi.cs
- src/Boleto.Net/Boleto/Boleto.cs
- src/Boleto.Net/BoletoImpressao/BoletoBancario.cs
- src/Boleto.Net/Html.Designer.cs
- src/Boleto.Net/Html.resx
Olá Boa tarde.
Fiz algumas alteração para possibilitar a impressão de boletos no formato carnê do banco sicredi.
- O Campo de desconto estava aplicado em 2 lugares do arquivo de remessa, desconto por dia de antecipação e também no desconto até vencimento. Separei em 2 propriedades diferentes.
- Não existia a opção de tipo de impressão a posição 004 do arquivo de remessa pede uma parâmetro "A" para normal e "B" para carnê estava fixado em "A".
- Não existia o parâmetro total parcelas quando solicitada a impressão em carnê as posições  075 a 078 pedem o numero da parcela e o total de parcelas. 
- Coloquei uma validação para o a propriedade tipoImpressao no banco Sicredi deve conter "A" ou "B"
Fiz também algumas adequações no canhoto do modo carnê de acordo com as sugestões do banco.
> Correções da Impressão Carne e Remessa Banco Sicredi

- src/Boleto.Net/Banco/Banco_Brasil.cs
Corrige erro na conversão da Data de inicio para Cobrança da Multa no método GerarDetalheRemessaCNAB400 para o Banco do Brasil.
> Erro na conversão da Data de inicio para Cobrança da Multa

- src/.vs/config/applicationhost.config
- src/Boleto.Net.MVC/Controllers/HomeController.cs
- src/Boleto.Net.MVC/Models/Exemplos.cs
- src/Boleto.Net.MVC/Views/Home/Index.cshtml
- src/Boleto.Net.Testes/BancoBradescoTeste.cs
- src/Boleto.Net/Banco/Banco_Bradesco.cs
- src/Boleto.Net/Boleto/Boleto.cs
- src/Boleto.Net/BoletoImpressao/BoletoNet.css
- src/Boleto.Net/BoletoImpressao/BoletoNetPDF.css
Boa tarde,
Fiz a correção da geração do boleto bradesco o qual irei utilizar agora, acredito que possamos continuar a revisão os outros boletos quando o boleto tem valor cobrado.
Fiz a correção e adicionei mais 2 testes unitários para o valor cobrado, nenhum teste que já existia foi quebrado.
Aproveitei também e adicionei no projeto de teste a geração por PDF, continuei na mesma pegada que já existia mais precisou de algumas alterações para não duplicar código.
Segue imagem abaixo como a tela de teste ficou:
> Correção boleto do bradesco para considerar o valor cobrado na linha digitável e no código de barras

- src/Boleto.Net/Util/Extensions.cs
Correção no método Right na classe Extensions.cs, pois está ocorrendo problema quando o tamanho da string passada por parâmetro é menor que o tamanho passado no segundo parâmetro, ocasionando erro ao obter a substring.
Sugerida correção conforme era feito quando se utilizava o método Strings.Right do namespace Microsoft.VisualBasic;
> Correção no método Right na classe Extensions.cs

- src/Boleto.Net/Html.resx
Alterando texto conforme determinação do Banco Central
*Conforme determinado pelo Banco Central do Brasil, por meio das circulares 3.598 e 3.656, em vigor a partir de 28/06/2013, Deve ser utilizadas às Novas Nomenclaturas nos boletos: Beneficiário: antigo Cedente, Pagador: antigo Sacado, Agencia\Código do Cedente:  **Agencia\Código do Beneficiário**, Recibo do Pagador: antigo Recibo do Sacado,  fica proibido boletos sem valor  e  sem vencimento,  ou com  as informações “Vencimento à vista” e “Contra apresentação”.*
> Alterando textos do layout do boleto

- src/Boleto.Net/Banco/Banco_Itau.cs
Validação necessária para leitura do arquivo retorno CNAB400 do banco Itaú quando o arquivo é do tipo 02RETORNO04EMPRESTIMO . 
Neste caso o campo valorAbatimento está vindo em branco, causando uma exception no momento da conversão para  inteiro. 
Segue um exemplo: 
[exemploRetornoEmprestimo.txt](https://github.com/BoletoNet/boletonet/files/1543671/exemploRetornoEmprestimo.txt)
> Valida valorAbatimento no método LerDetalheRetornoCNAB400 do Itau

- src/Boleto.Net/BoletoImpressao/BoletoBancario.cs
Fiz uma atualização no código de impressão de boleto Santander, carteira 101 (cobrança registrada).
Ocorria que na impressão saía a agência mas não o código da conta, ficando como "000000". Como também preciso que seja impresso o dígito, a alteração proposta resolve este caso.
> Impressão de boleto Santander, carteira 101

- src/Boleto.Net/Banco/Banco_Caixa.cs
Não dividia por 100 o campo ValorTitulo.
(Correção complementar à PR #664)
> Caixa: correção no parse do valor do título

- src/Boleto.Net/Banco/Banco_Itau.cs
Segue inclusão da carteira 104 para o Banco Itaú - ESCRITURAL ELETRÔNICA – CARNÊ
fixes #675
> #675 Banco Itaú Carteira 104

- src/.vs/config/applicationhost.config
- src/Boleto.Net/Banco/Banco_Bradesco.cs
- src/Boleto.Net/Boleto/EspecieDocumento/AbstractEspecieDocumento.cs
- src/Boleto.Net/Boleto/EspecieDocumento/EspecieDocumento.cs
- src/Boleto.Net/Boleto/EspecieDocumento/EspecieDocumento_BancoBrasil.cs
- src/Boleto.Net/Boleto/EspecieDocumento/EspecieDocumento_Banestes.cs
- src/Boleto.Net/Boleto/EspecieDocumento/EspecieDocumento_BankBoston.cs
- src/Boleto.Net/Boleto/EspecieDocumento/EspecieDocumento_Banrisul.cs
- src/Boleto.Net/Boleto/EspecieDocumento/EspecieDocumento_Bradesco.cs
- src/Boleto.Net/Boleto/EspecieDocumento/EspecieDocumento_Caixa.cs
- src/Boleto.Net/Boleto/EspecieDocumento/EspecieDocumento_Cecred.cs
- src/Boleto.Net/Boleto/EspecieDocumento/EspecieDocumento_CrediSIS.cs
- src/Boleto.Net/Boleto/EspecieDocumento/EspecieDocumento_Daycoval.cs
- src/Boleto.Net/Boleto/EspecieDocumento/EspecieDocumento_HSBC.cs
- src/Boleto.Net/Boleto/EspecieDocumento/EspecieDocumento_Itau.cs
- src/Boleto.Net/Boleto/EspecieDocumento/EspecieDocumento_Nordeste.cs
- src/Boleto.Net/Boleto/EspecieDocumento/EspecieDocumento_Real.cs
- src/Boleto.Net/Boleto/EspecieDocumento/EspecieDocumento_Santander.cs
- src/Boleto.Net/Boleto/EspecieDocumento/EspecieDocumento_Semear.cs
- src/Boleto.Net/Boleto/EspecieDocumento/EspecieDocumento_Sicoob.cs
- src/Boleto.Net/Boleto/EspecieDocumento/EspecieDocumento_Sicredi.cs
- src/Boleto.Net/Boleto/EspecieDocumento/EspecieDocumento_Sofisa.cs
- src/Boleto.Net/Boleto/EspecieDocumento/EspecieDocumento_Sudameris.cs
- src/Boleto.Net/Boleto/EspecieDocumento/EspecieDocumento_Votorantim.cs
- src/Boleto.Net/Properties/AssemblyInfo.cs
Basicamente foram realizadas alterações para obter o código da espécie do documento pela sigla. Essas alterações não afetam o que já existia de tratamento de espécie. Aqui, trabalhamos sempre com a sigla do documento, por serem comuns na maioria dos bancos.
Foi corrigido também um bug ao colocar as instruções nos detalhes de remessa 400 do banco bradesco.
> Alterações para Espécie de Documento

- src/Boleto.Net/Banco/Banco_Bradesco.cs
Atualmente quando se atribui ao boleto instruções do tipo "Instrucao_Bradesco" esta gerando erro na conversão para "Instrucao" neste foreach :
"BoletoNet.Instrucao não pode ser convertido em BoletoNet.Instrucao_Bradesco"
> Permitir o uso de Instrucao do tipo especifica ao banco Bradesco

- src/Boleto.Net/Banco/Banco_Sicredi.cs
Ao gerar remessa, a variável de código do cedente não era preenchida com a agência e código do posto (somente quando gerava o boleto), então o digito saía errado
> Digito verficador nosso número Sicredi

- src/Boleto.Net.Testes/BancoSantanderTeste.cs
- src/Boleto.Net.Testes/Retorno/NossoNumeroRetornoTeste.cs
- src/Boleto.Net/Banco/Banco_Santander.cs
Olá pessoal!
Precisei fazer a integração com o registro de boletos online do Santander, porém o Mod11 do nosso número no BoletoNet não bate com o que é retornado pelo serviço do Santander após o registro.
Segue imagem abaixo com a confirmação do Santander a respeito do registro.
> Alteração no calculo do digito verificador do nosso número.

- src/Boleto.Net/Banco/Banco_Caixa.cs
Pessoal, por favor, vamos prestar atenção ao alterarem os códigos. Os campos ValorTitulo e ValorPago não podem ser divididos por 100, pois já há no arquivo TRegistroEDI_Caixa_Retorno uma divisão nestes campos. ATENÇÃO!!!!
> Alteração Divisão por 100 no valor do título e valor pago

- .gitignore
- src/Boleto.Net.Arquivo/NBoleto.cs
- src/Boleto.Net/Banco/Banco_Itau.cs
- src/Boleto.Net/Properties/AssemblyInfo.cs
Foi comentada a linha que chama o método GerarMensagemVariavelRemessaCNAB400 do banco itaú (registro tipo 2) pois esse método gera registros de instrução incompatíveis com o manual, onde é mencionado somente dados de multa
> Alteração registro 2 itaú

- src/Boleto.Net/BoletoImpressao/BoletoBancario.cs
Possibilita ajustar a font-family do html.
```c#
boletoBancario.AjustaFamiliaFonte("Arial, Helvetica, sans-serif");
```
Tentei manter o código parecido ao máximo com o BoletoBancario.AjustaTamanhoFonte.
> Possibilitar ajuste de font-family

- .gitignore
- src/Boleto.Net/Banco/Banco_Caixa.cs
- src/Boleto.Net/Properties/AssemblyInfo.cs
Foram alterados campos no segmento R da Caixa, para colocar valor "0" ao invés de vazio, conforme manual do banco.
> Campos numéricos segmento R Caixa

- src/Boleto.Net/Banco/Banco_Unicred.cs
Estava gerando com 46 digitos ao invés de 44, então tirei o dv_cmpLivre para corrigir.
> Correção para o codigo de barras do Unicred

- src/Boleto.Net/Banco/Banco_Unicred.cs
A linha digitável nao pode usar a regra de cálculo do DV do barcode pois lá o nosso numero usa uma regra diferente para o DV
Mais uma correção para a saga Unicred
> Correção para linha digitável do Unicred

- src/Boleto.Net/Banco/Banco_Brasil.cs
- src/Boleto.Net/Banco/Banco_Unicred.cs
-Para o Banco Unicred, foi ajustado o cálculo do dígito verificador do nosso número e também ajustado o digito verificador geral do código de barras e linha digitável
- Para arquivo de Remessa do Banco do Brasil, foi possibilitado enviar o Juros de Mora na forma de Percentual
> Ajustes no cálculo do dígito verificador Banco Unicred e Remessa do Banco do Brasil

- src/Boleto.Net/Banco/Banco_Sicredi.cs
Corrigido rotina para composição do código do cedente, para não sofrer alteração quando este já conter 5 dígitos.
@brunoguelere , precisamos ter cuidado ao adicionar um campo ao código, que não é utilizado em mais nenhuma parte do mesmo código. Neste caso, vc adicionou o DigitoCedente à linha 68, e em nenhuma parte do mesmo código ele é preenchido ou referenciado, ou seja, quem não utiliza este campo preenchendo ele em seus respectivos sistemas, fica com erro!
> Corrigido rotina para composição do código do cedente.

- src/Boleto.Net/Banco/Banco_Sicoob.cs
Há empresas (como a minha) que utilizam o dígito do cedente diretamente no código do cedente.
> Alteração da rotina de validação para código de cedente com 7 dígitos

- src/Boleto.Net/BoletoImpressao/BoletoBancario.cs
Incluído o método "AjustaTamanhoLarguraBarcode", pois alguns clientes não conseguiam ler o barcode, em função de estar muito pequeno
> Opção para configurar a largura do barcode

- src/Boleto.Net/BoletoImpressao/BoletoBancario.cs
Ao preencher a variável OutrosAcrescimos nada acontecia.
Alterei esse trecho de código e tudo se resolveu.
Aparentemente os testes também.
Favor verificar se é uma correção valida para próxima release. o;)
> bugfix: Exibir corretamente valor do campo outros acrescimos

- src/Boleto.Net/Banco/Banco_Bradesco.cs
- src/Boleto.Net/Banco/Banco_Caixa.cs
- src/Boleto.Net/Banco/Banco_Itau.cs
- src/Boleto.Net/Banco/Banco_Semear.cs
- src/Boleto.Net/Banco/Banco_Uniprime.cs
- src/Boleto.Net/Boleto/Boleto.cs
O Problema:
Ao utilizar campos de descontos e acrescimos e chegar no ValorCobrado o sistema sempre acata o ValorBoleto 
A solução: 
Criar uma condição verificando se o valor ValorCobrado estiver preenchido utilizamos o ValorCobrado,
caso contrário utilizamos o ValorBoleto (retornado atualmente)
Exemplo:
Isso já era realizado para alguns bancos porém com a seguinte regra:
`var valor = boleto.ValorCobrado > boleto.ValorBoleto ? boleto.ValorCobrado : boleto.ValorBoleto;`
porém não concordo com essa regra, pois se o valor do documento for 1000,00 o valor do desconto/Abatimento for 200,00 logo o valor cobrado será de 800,00 e o valor do cod. de barras ainda ficaria incorreto.
Por esse motivo unifiquei essa regra e criei uma propriedade ReadOnly na classe principal simplificando a regra. …
> Valor CodBarras incorreto ao utilizar o campo ValorCobrado

- src/Boleto.Net/Banco/Banco_Caixa.cs
Segundo o manual, agora o Código do Cedente/Beneficiário pode conter até 7 dígitos. 
Manual:
[Manual_de_Leiaute_de_Arquivo_Eletronico_CNAB_240.pdf](https://github.com/BoletoNet/boletonet/files/8799217/Manual_de_Leiaute_de_Arquivo_Eletronico_CNAB_240.pdf)
> Novo padrão Código do Cedente/Beneficiário com 7 dígitos.

- src/Boleto.Net/Banco/Banco_Caixa.cs
Se o código do beneficiário tiver 7 dígitos, no código de barras e na linha digitável, não precisa de dígito verificador.
> Código de barras com código beneficiário 7 dígitos

- src/Boleto.Net/BoletoImpressao/BoletoBancario.cs
No boleto da CEF é necessário apresentar a palavra `Juros` junto com `Mora / Multa`.
> Adicionando a palavra 'Juros' no boleto da Caixa

- src/Boleto.Net.Testes/BancoSantanderTeste.cs
- src/Boleto.Net/Arquivo/ArquivoRemessaCNAB400.cs
Quando havia instrucao no boleto, estava incrementando incorretamente o numero de registros.
> Acerto erro numeroRegistros Instruções Santander

- src/Boleto.Net/Arquivo/ArquivoRemessaCNAB400.cs
- src/Boleto.Net/Banco/Banco_Bradesco.cs
Após PR https://github.com/BoletoNet/boletonet/pull/953, o programa não contava o número de registros corretamente para registros tipo 2 do Bradesco.
Utilizado mesmo padrão feito pelo @carloscds no Santander.
> Correção: Adicionada contagem de registros tipo 2 na remessa do CNAB 400 do Bradesco

- src/Boleto.Net/Banco/Banco_Safra.cs
Correção para o grupo 3 (Linha digitavel) do safra utilizar o Mod10 dos demais bancos ao invés de Modulo10 próprio.
Em casos onde o resto era zero, o DV assumia zero para o safra.
Abaixo um exemplo:
> Correção para o grupo 3 (Linha digitavel) do safra utilizar o Mod10

- src/Boleto.Net/BoletoImpressao/BoletoBancario.cs
Quebra o texto do pix copia e cola, para evitar problema do layout
Texto sem espaços, que distorce o layout
Layout após a correção
> Quebra a linha do pix se nao tiver espaço

- src/Boleto.Net/Banco/Banco_Daycoval.cs
Estava "0" e o correto, segundo documentação é "2". A impressão dos boletos, onde se informa o código do banco e seu digito verificador, ficará correta : "707-2"
> Correção digito verificador do código do Banco Daycoval

- src/Boleto.Net/Banco/Banco_Sicoob.cs
1. Realizado alteração no processo de geração de Header Remessa, posição de 33 a 52 para gerar com o código do convênio.
2. Posição 72 digito verificador da agencia deve ser Branco.
3. Posição 158 a 163 ajuste para considerar o parâmetro numeroArquivoRemessa sendo este controlado pelo cliente para identificar o número do arquivo de remessa que está sendo gerado para cada conta.
> #Fix arquivo remessa Sicoob, convênio, número sequencial header remessa.

- src/Boleto.Net/Banco/Banco_Uniprime.cs
A partir de 22 de fevereiro de 2025, o fator de vencimento será reiniciado para 1000, incrementando-se diariamente.
Da maneira que está hoje, o método FatorVencimento2000 está gerando um erro, foi está retornando mais de 4 caracteres para o fator de vencimento, não só pelo método mas também pelo data base, usar o método abstrato é suficiente para corrigir o problema, abaixo evidência do manual Sisprime..
> Correção Fator de vencimento Uniprime/Sisprime

- src/Boleto.Net/Arquivo/HeaderDeArquivoCNAB240.cs
No Santander, é possível que a hora do header venha com espaços
> No Santander, é possível que a hora do header venha com espaços
