BoletoNet/boletonet

- src/Boleto.Net/Banco/Banco_Caixa.cs
Alterações na classe Banco_Caixa: Criação de métodos GerarDetalheRemessa e GerarTrailerRemessa.
> Alterações na classe Banco_Caixa

- src/Boleto.Net/Boleto/Boleto.cs
Data do Documento nunca seria ajustada com essa condição.
> Correção em função de ajuste

- src/Boleto.Net.MVC/Boleto.Net.MVC.csproj
- src/Boleto.Net.sln
- src/Boleto.Net/Arquivo/DetalheSegmentoURetornoCNAB240.cs
- src/Boleto.Net/Banco/Banco_Santander.cs
Ocorre problema na conversao quando a dll esta hospedada em servidor fora do brasil;
mes-dia-ano
dataOcorrencia.ToString("##-##-####")
> Converter string em data, Retorno Santander 240

- src/Boleto.Net/Banco/Banco_Sicoob.cs
Alterado rotinas de geração de remessa e retorno para contemplar a modalidade do boleto, que no sicoob é utilizada
> Atualização rotinas de retorno e remessa Sicoob

- src/Boleto.Net.Testes/BancoBradescoTeste.cs
- src/Boleto.Net/Banco/Banco_Bradesco.cs
Considerar a carteira 25 do banco bradesco:
25 - Sem Registro - Emissão na Internet
> implementação da carteira 25 bradesco 

- src/Boleto.Net.Testes/BancoBradescoTeste.cs
- src/Boleto.Net/Banco/Banco_Bradesco.cs
26 - Com Registro - Emissão na Internet
> Considerar a carteira 26 do banco bradesco

- src/Boleto.Net/Boleto/EspecieDocumento/EspecieDocumento.cs
- src/Boleto.Net/BoletoImpressao/BoletoBancario.cs
Adicionado mais bancos na função CarregaTodas da EspecieDocumento.
Adicionado campo número do endereço do sacado na impressão do boleto.
> EspecieDocumento e número endereço do sacado.

- src/Boleto.Net/Banco/Banco_Bradesco.cs
- src/Boleto.Net/Banco/Banco_Brasil.cs
- src/Boleto.Net/Banco/Banco_Itau.cs
- src/Boleto.Net/Banco/Banco_Santander.cs
Só inicializar local de pagamento quando estiver null. Bancos: Bradesco,
Brasil, Itaú e Santander.
> Só inicializar local de pagamento quando estiver null.

- src/Boleto.Net/Boleto/Cedente.cs
- src/Boleto.Net/BoletoImpressao/BoletoBancario.cs
> Imprimir o CPFCNPJ do cedente com máscara

- src/Boleto.Net/Boleto/Instrucao/Instrucao.cs
Adicionado case para criar instrução Sicredi.
> Construtor de instrução Sicredi

- src/Boleto.Net/Banco/Banco_Bradesco.cs
- Para utilizar a interface IIntrucao e não a classe Instrucao_Bradesco facilitando o uso externo;
- Implementada utilização da propriedade boleto.Remessa.CodigoOcorrencia afim de permitir outros códigos de ocorrência além do código "01";
> Melhorias no método GerarDetalheRemessaCNAB400 do Bradesco

- src/Boleto.Net/Banco/Banco_Caixa.cs
- src/Boleto.Net/Banco/Banco_Nordeste.cs
Corrigido funções para validar e gerar arquivo de remessa para CAIXA, layout 400, no arquivo Banco_Caixa.
Corrigido erro de ambiguidade entre Strings no arquivo Banco_Nordeste.
> Correção remessa CAIXA, layout 400

- src/Boleto.Net/Banco/Banco_Cecred.cs
Boleto CECRED - Módulo 11
Ajustado conforme manual CNAB 400_11-2014.pdf pagina 12. diz para retornar 1, caso 0 ou 1
> Signed-off-by: Edson <edsonfast@gmail.com>

- src/Boleto.Net.MVC/Models/Exemplos.cs
- src/Boleto.Net/BoletoImpressao/BoletoBancario.cs
- src/Boleto.Net/Html.Designer.cs
- src/Boleto.Net/Html.resx
Criação do parâmetro tamanhoFonteInstrucoes para o método AjustaTamanhoFonte da classe BoletoBancario
> Atualização tamanhoFonteInstrucoes para o método AjustaTamanhoFonte

- src/Boleto.Net/Banco/Banco_Itau.cs
Testes realizados em sistema de produção.
Empresa RVB recebendo dinheiro corretamente. :+1:
> Ajustes para montagem de código de barras Banco Itaú Carteira 112

- src/Boleto.Net/Arquivo/ArquivoRemessaCNAB240.cs
- src/Boleto.Net/Banco/Banco_Cecred.cs
- src/Boleto.Net/Boleto.Net.csproj
- src/Boleto.Net/BoletoImpressao/BoletoBancario.cs
Novos ajustes no layout 240 registro R
> Boleto CECRED 240 Registro R

- src/Boleto.Net/Arquivo/ArquivoRemessaCNAB240.cs
- src/Boleto.Net/Arquivo/ArquivoRemessaCNAB400.cs
- src/Boleto.Net/Arquivo/DetalheSegmentoYRetornoCNAB240.cs
- src/Boleto.Net/Arquivo/LinhaDeArquivoGeradaArgs.cs
- src/Boleto.Net/Arquivo/LinhaDeArquivoLidaArgs.cs
- src/Boleto.Net/Banco/AbstractBanco.cs
- src/Boleto.Net/Banco/Banco.cs
- src/Boleto.Net/Banco/Banco_Santander.cs
- src/Boleto.Net/Banco/IBanco.cs
- src/Boleto.Net/Boleto.Net.csproj
- src/Boleto.Net/Boleto/Cedente.cs
- src/Boleto.Net/Boleto/Remessa.cs
Criação dos segmentos P, Q, R e S na remessa do Santander.
Criação dos segmentos Y e U na remessa do Santander.
Inclusão da carteira 102 (sem registro) do Santander.
Outras correções e melhorias.
> Atualizações e Correções Santander

- src/Boleto.Net/Boleto/Instrucao/Instrucao_Bradesco.cs
As novas Instrucoes sao os valores do boleto original e o valor do boleto caso o cliente pague com desconto
> Inclui novas Instrucoes para o Banco Bradesco

- src/Boleto.Net/Banco/Banco_Itau.cs
Removida a redundância da mensagem.
> [Itau] - Alterado texto referente ao Local de Pagamento

- src/Boleto.Net/Banco/Banco_Brasil.cs
Atualizações do banco do BB para homologação da remessa e retorno com o
banco
Pedido de Baixa do Banco do Brasil Cariteira 17. Revision 13028 e 13039.
4484 - Ao processar o retorno do banco do brasil, não está conseguindo
encontrar os títulos através do nosso número. Revision 17461.
4476 - Chamado: 180409 ao processar um retorno de teste do banco do
Brasil, carteira 17, o retorno de pagamento não processa, ocorre o erro
de conversão de string para int. Revision 17479.
Correções na geração de trailer de lote de remessa. Revision 17516.
Formatação no campo do valor do boleto na geração do detalhe do segmento
P na remessa. Revision 17850.
Configuração para que o segmento P de detalhe da remessa fique
maiúsculo. Revision 17976.
> Atualizações do banco do BB para homologação da remessa e retorno com o banco

- src/Boleto.Net/Banco/Banco_Sicredi.cs
Alteração no arquivo CNAB400 da Sicredi permitindo Porcentagem de Juros Mora além do Valor.
> Alteração no arquivo CNAB400 da Sicredi permitindo Porcentagem de Juros Mora.

- src/Boleto.Net.Arquivo/Main.cs
- src/Boleto.Net/Banco/Banco_Nordeste.cs
- src/Boleto.Net/Boleto.Net.csproj
- src/Boleto.Net/EDI/Banco/TRegistroEDI_Banco_Nordeste_Retorno.cs
Add Registro EDI com base no Banco do Brasil ```TRegistroEDI_Banco_Nordeste_Retorno.cs```
Implementado no Projeto de Teste ```Boleto.Net.Arquivo```
> Implementação Retorno Banco do Nordeste CNAB400

- src/Boleto.Net/BoletoImpressao/BoletoBancario.cs
Adição método para recuperar logos dos bancos
> Adição método para recuperar logos dos bancos

- src/Boleto.Net/Banco/Banco_Bradesco.cs
Obtém a descrição da ocorrência através da função já existente no banco Bradesco.
> Descrição da ocorrência do retorno de 400 posições | Bradesco

- src/Boleto.Net/Banco/Banco_Santander.cs
Correção Leitura Segmento U - Santander
Revision 13361.
> Correção Leitura Segmento U - Santander

- src/Boleto.Net/Banco/Banco_Sicoob.cs
- src/Boleto.Net/Boleto/Instrucao/Instrucao_Sicoob.cs
- Alteração do fator de vencimento, correção solicitada durante a
homologação com o banco, revision 12857 e 12861.
- Arquivo de retorno, Sicooob, carteira 1 - Linha de Baixa.
- Inclusão do Cnab 400 Segmento T e U, revision 14009.
- Remessa Sicoob 240
* Criação do header
* Criação do lote da remessa
* Criação do detalhe
* Criação do segmento R
* Criação do trailer do lote
* Criação do trailer da remessa
- Na especificação do banco é solicitado sempre incluir o código do
convênio em branco, revision 17519.
- Inclusão do dígito da agência em homologação com o banco, revision
17946.
- Em homologação com o banco, foi solicitado a remoção do dígito do
cedente para cálculo do mod11.
- 4774 - Chamado 191133 - Críticas na homologação do boleto Sicoob,
revision 18257.
- Mudança da criação da linha …
> Boleto e Remessa Sicoob

- src/Boleto.Net/Banco/Banco_Santander.cs
Correção da mensagem para exceções da geração de detalhes do segmento S
da remessa Santander.
> Correção da mensagem

- src/Boleto.Net/Banco/Banco_Sicoob.cs
Correção para retirada do if, pois sempre que tem formatar nosso numero
> Correção para retirada do if, pois sempre que tem formatar nosso numero

- src/Boleto.Net/Boleto.Net.csproj
- src/Boleto.Net/Boleto/CodigoMovimento/CodigoMovimento.cs
- src/Boleto.Net/Boleto/CodigoMovimento/CodigoMovimento_Itau.cs
> Implementação códigos de movimentos Itaú

- src/.vs/config/applicationhost.config
- src/Boleto.Net/Arquivo/ArquivoRemessaCNAB400.cs
- Corrigido o contador de numeroDoRegistro na remessa CNAB 400, quando existem linhas de instrução,
> Corrigido o contador "numeroRegistro" na remessa CNAB 400 com linhas de instrução

- src/Boleto.Net/Banco/Banco_Caixa.cs
Correção do arquivo retorno CAIXA CNAB240 para pegar o código da ocorrência sacado (Cód. Mov. Retorno).
> Correção do arquivo retorno CAIXA CNAB240 - Código Ocorrência

- src/Boleto.Net/Arquivo/ArquivoRemessaCNAB400.cs
- src/Boleto.Net/Banco/Banco_Bradesco.cs
- src/Boleto.Net/Banco/Banco_Itau.cs
- src/Boleto.Net/Banco/Banco_Sicoob.cs
Correções dos registros de detalhes para bancos Bradesco, Itaú e Sicoob.
> Correções de erros Detalhe Remessa

- src/Boleto.Net.Testes/BancoSicredi/BancoSicrediTeste.cs
- src/Boleto.Net/Banco/Banco_Sicredi.cs
Formatação do nosso número para impressão e removido formatação na exportação da remessa seguindo padrão de outros bancos
> SICREDI - Formatação do nosso número para impressão

- src/Boleto.Net/BoletoImpressao/BoletoBancario.cs
Hello BoletoNet developers,
Our enterprise is interested in using your project for generate boletos for our clients in Brazil. However, we have noticed that in two of your functions the streams are not closed, and this matter could be a problem on our servers if we have an important amount of requests.
We have made some chages to correct this issue. If you could add these changes to your project we would be grateful.
Best regards,
Maties
(Integration Specialist at Xml Travelgate)
> Added stream close in MontaHtmlEmbedded and ObterLogoDoBanco

- src/Boleto.Net/BoletoImpressao/BoletoBancario.cs
- src/Boleto.Net/BoletoImpressao/BoletoNet.css
- src/Boleto.Net/BoletoImpressao/BoletoNetPDF.css
- src/Boleto.Net/Html.Designer.cs
- src/Boleto.Net/Html.resx
Adicionado dois Parametros BoletosPorPagina e ZoomPercent - Dessa forma é possivel controlar a quebra de página por número de boletos como também o Zoom/Scale para ajustes finos na página.
> Melhoria na função MontaBytesListaBoletoPDF.

- src/Boleto.Net/Banco/Banco_Brasil.cs
- src/Boleto.Net/Banco/Banco_Cecred.cs
- src/Boleto.Net/Banco/Banco_Sicredi.cs
- SICREDI - Descrição da Ocorrência e preenchimento do campo Conta e DACConta nos registros de detalhe
- SICREDI e CECRED - Descrição da Ocorrência/CodigoMovimento
- BB - Remessa 240 - Ajustado Header 240 que tinha 2 espaços a mais após variação da carteira gerando 242 colunas no header
> SICREDI - CECRED - BB

- src/Boleto.Net/Banco/Banco.cs
- src/Boleto.Net/Banco/Banco_Caixa.cs
- src/Boleto.Net/Boleto/Boleto.cs
- src/Boleto.Net/Boleto/CodigoRejeicao/CodigoRejeicao.cs
- src/Boleto.Net/Boleto/CodigoTarifas/CodigoTarifas.cs
- src/Boleto.Net/Boleto/EspecieDocumento/EspecieDocumento.cs
- src/Boleto.Net/Boleto/Instrucao/Instrucao.cs
> resolve #526

- src/Boleto.Net/Banco/Banco_Daycoval.cs
- src/Boleto.Net/Boleto/Instrucao/Instrucao.cs
O banco Daycoval havia reportado os seguintes problemas, após as alterações propostas neste PR o banco aprovou a emissão de boletos e o arquivo de remessa CNAB400.
ACERTO NO DETALHE Posicao 063 a 070 - DEVE SER INFORMADO NOSSO NUMERO SEM DV. FAVOR, INICIAR EM 1001.
ACERTO NO DETALHE Posicao 076 a 083 DEVE SER INFORMADO O NOSSO NUMERO SEM DV
ACERTO NO DETALHE Posição 161 a 173 devem ser zeros - Juros de Mora deve ser encaminhado por email ao gerente Daycoval para cadastro fixo em sistema (Juros a.m.)
> Modificações solicitadas pelo banco Daycoval

- src/Boleto.Net/Banco/Banco_Bansirul.cs
Correção para Constante 40 (agência com 4 dígitos) do Banrisul
> Correção para constante 40

- src/Boleto.Net/Banco/Banco_Sicredi.cs
Lista de Motivos de rejeição para arquivo retorno do Banco SICREDI.
Adicionado os motivos em forma de LISTA usando generics e posteriormente lido usando LINQ.
> Criacao do retorno de motivos de rejeição para o banco SICREDI

- src/Boleto.Net/Banco/Banco_Mercantil.cs
Adicionando a implementação da geração de boletos para o banco Mercantil do Brasil.
> Criando Banco_Mercantil.cs

- src/.vs/config/applicationhost.config
- src/Boleto.Net.Arquivo/Main.Designer.cs
- src/Boleto.Net.Arquivo/Main.cs
- src/Boleto.Net.Arquivo/NBoleto.cs
- src/Boleto.Net/Banco/Banco_Sicredi.cs
- src/Boleto.Net/Boleto/Boleto.cs
- src/Boleto.Net/BoletoImpressao/BoletoBancario.cs
- src/Boleto.Net/Html.Designer.cs
- src/Boleto.Net/Html.resx
Olá Boa tarde.
Havia deixado um erro na validação no ultimo request coloquei uma porta OR no Lugar de uma AND.
> Correção Validação Sicredi

- src/Boleto.Net.Testes/BancoBradescoTeste.cs
- src/Boleto.Net/Banco/Banco_Bradesco.cs
- src/Boleto.Net/Boleto/Endereco.cs
Endereço do sacado com número e agência no retorno
> BRADESCO 400 - Endereço do sacado com número

- src/Boleto.Net/Banco/Banco_Bansirul.cs
- src/Boleto.Net/Banco/Banco_Brasil.cs
- src/Boleto.Net/Banco/Banco_Daycoval.cs
- src/Boleto.Net/Banco/Banco_Itau.cs
- src/Boleto.Net/Banco/Banco_Santander.cs
- src/Boleto.Net/Banco/Banco_Sicoob.cs
- src/Boleto.Net/Banco/Banco_Sicredi.cs
- src/Boleto.Net/Boleto/Endereco.cs
Incluir numero e complemento do endereco do sacado no arquivo de remessa CNAB400
> Número e complemento end Sacado no arquivo CNAB400

- src/Boleto.Net/Arquivo/ArquivoRetornoCNAB400.cs
- src/Boleto.Net/Arquivo/DetalheRetorno.cs
- src/Boleto.Net/Arquivo/HeaderRetorno.cs
- src/Boleto.Net/Banco/AbstractBanco.cs
- src/Boleto.Net/Banco/Banco_Bansirul.cs
- src/Boleto.Net/Banco/Banco_Bradesco.cs
- src/Boleto.Net/Banco/Banco_Caixa.cs
- src/Boleto.Net/Boleto.Net.csproj
- src/Boleto.Net/EDI/Banco/TArquivoBanrisulRetorno_EDI.cs
- src/Boleto.Net/EDI/Banco/TArquivoCaixaRetorno_EDI.cs
- src/Boleto.Net/EDI/Banco/TRegistroEDI_Banrisul_Retorno.cs
- src/Boleto.Net/EDI/Banco/TRegistroEDI_Caixa_Retorno.cs
- src/Boleto.Net/EDI/EDIBasicTypes.cs
- src/Boleto.Net/Enums/Bancos.cs
Correções nas leituras dos arquivos retorno do Banrisul e da Caixa e melhorias pontuais na organização de alguns pontos do código.
> Correção Arquivos Retorno

- src/Boleto.Net/Banco/Banco_Caixa.cs
Correção boleto da Caixa para considerar o valor cobrado na linha digitável e no código de barras.
> Correção boleto da Caixa para considerar o valor cobrado 

- src/Boleto.Net/Banco/Banco_Brasil.cs
Correção na validação do tamanho máximo do campo  ‘nosso número’ para o layout do banco do brasil
> Correção na validaçao do banco do Brasil

- src/Boleto.Net/Util/Utils.cs
> Adjusts for issue #631

- src/.vs/config/applicationhost.config
- src/Boleto.Net/Banco/Banco_Caixa.cs
> Quando na remessa da caixa possuir valor no campo desconto

- src/Boleto.Net/Banco/Banco_Brasil.cs
- src/Boleto.Net/Banco/Banco_Caixa.cs
- src/Boleto.Net/Banco/Banco_Santander.cs
Lembrando que o número do documento ainda está sendo informado no arquivo, porém nas posições pertinentes à ele, ou seja, ele estava sendo informado mais de uma vez no arquivo
> Número do Documento -> Número de Controle

- src/Boleto.Net/Banco/Banco.cs
- src/Boleto.Net/Banco/Banco_Maxima.cs
- src/Boleto.Net/Boleto.Net.csproj
- src/Boleto.Net/Enums/Bancos.cs
Incluído Banco Máxima (243) e a possibilidade de geração do arquivo CNAB 240.
> Inclusão CNAB 240 para Banco Máxima

- src/Boleto.Net/Boleto/EspecieDocumento/EspecieDocumento.cs
Inclusão da especie de documento padrão Banestes
> Inclusão da especie de documento padrão Banestes

- src/Boleto.Net/Boleto/EspecieDocumento/EspecieDocumento_Banestes.cs
O valor do código de DuplicataMercantil deveria ser "1".
> Correcao do codigo de DuplicataMercantil

- src/Boleto.Net/Banco/Banco_Bansirul.cs
Conforme solicitação do Banrisul
> Atualização do local de pagamento

- src/Boleto.Net/Banco/Banco_Bradesco.cs
Na linha 2, os campos data de desconto2, valor de desconto 2, data de desconto 3 e valor de desconto 3, desem ser preenchidos com 0
> Correção de data de desconto e valores na linha 2

- src/Boleto.Net/Boleto/CodigoMovimento/CodigoMovimento_Itau.cs
Adicionado mais códigos de ocorrências nos movimentos
> Adicionado mais códigos de ocorrencias

- src/Boleto.Net/Banco/Banco_Caixa.cs
Descomentado campo carteira, posição 57 (2 caracteres) na linha 1666
> Descomentado campo carteira,

- src/Boleto.Net/EDI/Banco/TRegistroEDI_Caixa_Retorno.cs
Corrigido valor do Título e Valor Pago
> Corrigido valor do Título e Valor Pago

- src/Boleto.Net/Banco/Banco_Caixa.cs
Atualização Caixa para Valor do Título e Valor Pago, corrigido arquivo TRegistroEDI_Caixa_Retorno também
> Atualização Caixa para Valor do Título e Pago

- src/Boleto.Net/Banco/Banco_Sicoob.cs
Corrigido campos para geração de remessa CNAB240 sicoob de acordo com layout.
> Atualização Sicoob

- src/Boleto.Net/Boleto/CodigoMovimento/CodigoMovimento_Itau.cs
Adicionado o código de ocorrência 81
> Adicionada Ocorrência 81

- src/Boleto.Net/Boleto/CodigoMovimento/CodigoMovimento_Itau.cs
Adicionado o código de ocorrência 94
> Adicionado Ocorrência 94

- src/Boleto.Net.Arquivo/Main.cs
- src/Boleto.Net/Banco/Banco_Caixa.cs
O método para gerar o segmento R da caixa estava sem a verificação se a carteira é SIG ou não, então gerava segmento com erro
> Caixa Segmento R

- .gitignore
- src/Boleto.Net/Banco/Banco_Bradesco.cs
- src/Boleto.Net/Banco/Banco_Brasil.cs
- src/Boleto.Net/Banco/Banco_Caixa.cs
- src/Boleto.Net/Banco/Banco_Itau.cs
- src/Boleto.Net/Banco/Banco_Semear.cs
- src/Boleto.Net/Properties/AssemblyInfo.cs
Basicamente foi alterado a verificação de mensagem padrão "Até o vencimento, preferencialmente no ", pois em alguns bancos o nome não aparecia após essa mensagem
> Alterações no local de pagamento

- src/Boleto.Net/Boleto/CodigoMovimento/CodigoMovimento_Sicoob.cs
CodigoMovimento_Sicoob - 25 está faltando e ocorrendo erro ao ler o retorno quando o registro vem com esta ocorrência.
> CodigoMovimento_Sicoob - 25 está faltando

- src/.vs/config/applicationhost.config
- src/Boleto.Net/Banco/Banco_Itau.cs
Alteração para retorno CNAB 240 Itau - Quando ocorrencia 54, campo DataVencimento vem 0
> Alteração para retorno CNAB 240 Itau - Ocorrencia 54

- src/Boleto.Net.Testes/BancoSantanderTeste.cs
- src/Boleto.Net/Banco/Banco_Santander.cs
Terminei de homologar agora a linha digitável do santander, no meu PR anterior tinha uma inconsistência.
> Correção da linha digitável do Santander

- src/Boleto.Net/Banco/Banco_Itau.cs
Sacador / Avalista, deve ser o Cedente. Estava com os dados do Sacado
> Sacador / Avalista, deve ser o Cedente

- src/.vs/config/applicationhost.config
- src/Boleto.Net/Banco/Banco_Santander.cs
Correção posição 42 a 65 Santander, deve ser brancos
> Correção posição 42 a 65 Santander, deve ser brancos

- src/Boleto.Net/Banco/Banco_Unicred.cs
Adicionada diferenciação para cálculo do nosso numero
> Correção p/ calculo do DV do nosso numero Unicred

- src/Boleto.Net.Arquivo/EnviarEmail.cs
- src/Boleto.Net.Arquivo/NBoleto.cs
- src/Boleto.Net.Testes/BancoVotorantimTeste.cs
- src/Boleto.Net/Arquivo/AbstractArquivoRemessa.cs
- src/Boleto.Net/Arquivo/AbstractArquivoRetorno.cs
- src/Boleto.Net/Arquivo/ArquivoRetornoCNAB240.cs
- src/Boleto.Net/Arquivo/LinhaDeArquivoGeradaArgs.cs
- src/Boleto.Net/Arquivo/LinhaDeArquivoLidaArgs.cs
- src/Boleto.Net/Banco/Banco_Sicredi.cs
- src/Boleto.Net/Boleto/CodigoLiquidacao/CodigoLiquidacao.cs
- src/Boleto.Net/Boleto/CodigoMovimento/CodigoMovimento_BancoBrasil.cs
- src/Boleto.Net/Boleto/CodigoMovimento/CodigoMovimento_Caixa.cs
- src/Boleto.Net/Boleto/CodigoMovimento/CodigoMovimento_Cecred.cs
- src/Boleto.Net/Boleto/CodigoMovimento/CodigoMovimento_Itau.cs
- src/Boleto.Net/Boleto/CodigoMovimento/CodigoMovimento_Nordeste.cs
- src/Boleto.Net/Boleto/CodigoMovimento/CodigoMovimento_Sicoob.cs
- src/Boleto.Net/Boleto/CodigoMovimento/CodigoMovimento_Sicredi.cs
- src/Boleto.Net/Boleto/CodigoRejeicao/CodigoRejeicao.cs
- src/Boleto.Net/Boleto/CodigoTarifas/CodigoTarifas.cs
- src/Boleto.Net/Boleto/EspecieDocumento/EspecieDocumento.cs
- src/Boleto.Net/Boleto/Sacado/InfoSacado.cs
- src/Boleto.Net/Util/C2of5i.cs
to learn more about https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/readonly
> 🚧 Add read-only keyword

- src/Boleto.Net/Banco/Banco_Bansirul.cs
Reverts BoletoNet/boletonet#868
> Revert "🚧 fix || operator"

- src/Boleto.Net/Banco/Banco_Sicredi.cs
- src/Boleto.Net/Boleto/CodigoMovimento/CodigoMovimento_Sicredi.cs
Novos códigos de movimento Maio 2020 v1.6
> Sicredi - Codigo de Movimento Maio 2020 v1.6

- src/Boleto.Net/Banco/Banco_Caixa.cs
Boa tarde, em processo de homologação com a caixa, me cobraram que fosse informado na posição 84 o tipo de desconto que seria aplicado. No caso estou enviando como 0 (sem desconto) se a data do desconto nao foi informada e 1 (Valor Fixo) caso tenha sido informado a data do desconto. 
Segue o link de retorno de validação da caixa:
[https://tomticket-anexos.s3.amazonaws.com/71443c1c9f5c5b10990029658e3a08c8a5bdf9bc2ee6212be568cd5ae6eb0c34/cdd934fa5a0ff0b114507f1b540cdf4f4999d658f75da3137354d2a027498c60/Relat%C3%B3rio%20CNAB%20400.html](url)
Por favor se possível gerar uma versão para eu implantar o cliente, agradeço!
> Homologacao CAIXA - DetalheCNAB400

- src/Boleto.Net.MVC/Boleto.Net.MVC.csproj
- src/Boleto.Net.MVC/Web.config
- src/Boleto.Net.MVC/packages.config
- src/Boleto.Net/Banco/Banco_Itau.cs
- src/Boleto.Net/BoletoImpressao/BoletoBancario.cs
Erro ao gerar remessa com avalista null e na impressão do boleto corrigido a "Agencia/Cod. Beneficário" para os padroes do manual de integracao que é a Agencia e a conta com o dv.
> Erros itau

- src/Boleto.Net.Testes/BancoBrasil/BancoBrasilCarteira18019Teste.cs
- src/Boleto.Net.Testes/BancoBrasil/BancoBrasilCarteira18Teste.cs
- src/Boleto.Net.Testes/BancoItau/BancoItauTeste.cs
- src/Boleto.Net.Testes/BancoSantanderTeste.cs
- src/Boleto.Net.Testes/BancoUnicredTeste.cs
- src/Boleto.Net/Banco/Banco_Unicred.cs
> Atualizacao Testes

- src/Boleto.Net/Banco/Banco_Safra.cs
Banco Safra Homologado para geração de arquivo Remessa e validação de boletos
> Geração de arquivo Remessa banco Safra

- src/Boleto.Net/Banco/Banco_Itau.cs
Adicionado suporte a carteira 138 ao banco Itaú
> Adicionado suporte a carteira 138 ao banco Itaú

- README.md
- src/Boleto.Net.Testes/BancoUniprimeTeste.cs
- src/Boleto.Net/Banco/Banco_Banestes.cs
- src/Boleto.Net/Banco/Banco_Bradesco.cs
- src/Boleto.Net/Banco/Banco_Caixa.cs
- src/Boleto.Net/Banco/Banco_Sicoob.cs
- src/Boleto.Net/Banco/Banco_Uniprime.cs
- src/Boleto.Net/Boleto.Net.csproj
- src/Boleto.Net/Boleto/Boleto.cs
- src/Boleto.Net/Enums/TipoEmissao.cs
Alteração da propriedade ApenasRegistrar para TipoEmissao
> Alteração da propriedade ApenasRegistrar para TipoEmissao

- src/Boleto.Net/Boleto/CodigoMovimento/CodigoMovimento_Sicoob.cs
Adicionado código 48 aos movimentos do Sicoob
> Adicionado código 48 aos movimentos do Sicoob

- src/Boleto.Net/Banco/Banco_Itau.cs
Correções apontadas em homologação de boleto Itaú junto ao banco.
> Correções Itaú

- src/Boleto.Net/Banco/Banco_Brasil.cs
- Alterado para primeiro pegar DataJurosMora, e depois Data Vencimento
> Resolvido Issue #976

- src/Boleto.Net/Banco/Banco_Safra.cs
Segundo o manual do Safra e após passar por homologação:
Criei uma variação para cálculo do mod10 no banco safra.
Para nao ter problema de retrocompatibilidade, o novo cálculo será chamado apenas se utilizar a VariacaoCarteira = "1"
SE RESTO = ZERO, DEIXAR O VALOR DE ZERO, CASO CONTRATARIO SUBTRAIR 10 - RESTO
> Novo cálculo do Mod10 no Banco_Safra.cs

- src/Boleto.Net.Testes/BancoItau/BancoItauTeste.cs
- src/Boleto.Net/Boleto/Boleto.cs
- src/Boleto.Net/BoletoImpressao/BoletoBancario.cs
- src/Boleto.Net/Html.Designer.cs
- src/Boleto.Net/Html.resx
Adição da nova propriedade TituloAvalista para que se possa personalizar o label do boleto.
> #992 - Possibilidade de trocar o Label do Beneficiário Final para Sacador / Avalista

- src/Boleto.Net/Arquivo/ArquivoRetornoCNAB240.cs
- src/Boleto.Net/Arquivo/DetalheSegmentoURetornoCNAB240.cs
- src/Boleto.Net/Banco/Banco_Sicoob.cs
- src/Boleto.Net/Banco/Banco_Sicredi.cs
- src/Boleto.Net/Boleto/EspecieDocumento/EspecieDocumento_Sicredi.cs
#Retorno CNAB240, numero remessa arquivo em DetalheRetorno.NumeroSequencial.
#Retorno SICREDI CNAB240, SegmentoU problema com datas (crédido e ocorrência sacado) quando retorno for espaços. #Remessa SICOOB CNAB240, SegmentoQ código da ocorrência respeitando o informado em boleto.Remessa.CodigoOcorrencia. #Retorno SICOOB CNAB240, SegmentoT código rejeição e uso febraban. 
#Remessa SICREDI CNAB240, SegmentoP, TrailerArquivo, LoteRemessa, ajustes HeaderRemessa
> Ajustes arquivo remessa e retorno SICOOB e SICREDI

- src/Boleto.Net/Arquivo/HeaderDeArquivoCNAB240.cs
Adição de novas Ocorrencias no Sicoob
> Adição de novas Ocorrencias no Sicoob
